### ISSUE TITLE
Win10AU support

### ISSUE THREAD

**Issue by k-takata** [k-takata/TClockLight#1]
Doesn't work on Windows 10 Anniversary Update.

The following error message is shown:
`failed to start TClock.: 6`

**Comment by k-takata** [comment]
`topic/win10au` ブランチで作業中。
https://github.com/k-takata/TClockLight/tree/topic/win10au

**Comment by k-takata** [comment]
エラーメッセージは、TClock Light起動時に、時計のウィンドウがすでにサブクラス化されている場合に表示される。安全性のためのチェックだが、Win10AUでは外さざるを得ないと思われる。
サブクラス化には、従来の `SubclassWindow` ではなく、`SetWindowSubclass` を使う方法を試行中。
Win9x向けの古いコードは一部無効化。

tclock.exe を実行しても、すぐには表示が切り替わらず、マウスを時計の領域に持って行くとようやく表示が切り替わる現象が発生。
時計のウィンドウサイズが変更されない。
左クリックをしても、カレンダーが表示されない。

**Comment by k-takata** [comment]
http://homepage1.nifty.com/kazubon/progdoc/tclock/kyogo.html

> TClock Light（031201以降）では、ほかのTClock型のソフトウェア（タスクバーの各パーツをサブクラス化するソフトウェア）との競合を防ぐため、「すでにサブクラス化されているウィンドウはサブクラス化しない」という対策を取っています。

**Comment by k-takata** [comment]
> tclock.exe を実行しても、すぐには表示が切り替わらず、マウスを時計の領域に持って行くとようやく表示が切り替わる現象が発生。

CallWndProc() の中で、ウィンドウメッセージの hwnd が時計の hwnd と一致しているかをチェックして、一致していたら時計の改造を開始するようになっていたが、無視してすぐに改造を開始するようにした。 bf332f136cb54cb76b55d22d1d54b33f80bb30de

**Comment by kewlfft** [comment]
takata I am very interested in your resolution of the AU issue. Let me know if you have a working binary or if you need help for testing. My japanese is limited.

**Comment by k-takata** [comment]
You may want to try this binary: https://github.com/k-takata/TClockLight/releases/tag/tclocklight-kt160809-alpha

Currently there are some problems:
- Sometimes the clock flickers. (E.g. when the number of icons in the notify area is changed.)
- Calendar is not shown when a user clicks the clock.
- The layout of properties window is not good on a High DPI environment.
- The clock size is not properly changed when a timer is used.

**Comment by kewlfft** [comment]
great to have it back 
i have noticed the flickering you mention also:
- when i click on a taskbar button, part of the clock goes blank until the next refresh (up to 1 sec)
- dynamic resizing hides the notification icon: when i change USTR0 (I use customized format and update USTR0 to 3 with my own program) to something that takes more space it shifts the clock to the right and hides part of the notification icon. If I click on the notification icon things are rearranged and the clock shifts back left.

**Comment by kewlfft** [comment]
by the way thank you Takata san for your long term support of TClockLight that I have been using for more than 10 years

**Comment by k-takata** [comment]
> by the way thank you Takata san for your long term support of TClockLight that I have been using for more than 10 years

I'm glad to see this comment. ;-)

BTW, the flickering and resizing problems seems to be almost fixed with the latest commit on `topic/win10au` branch. (Maybe the flickering problem cannot be fixed perfectly.)
The binary is not available yet.

**Comment by kewlfft** [comment]
ok looking forward to it, i have been using the new binaries for one week with no major issue except these flickering and resizing minor issues

**Comment by k-takata** [comment]
New release is available: https://github.com/k-takata/TClockLight/releases/tag/tclocklight-kt160827-beta

Now the `topic/win10au` branch is merged into the master branch.

**Comment by kewlfft** [comment]
great job Takata the new release fixes the resizing issues and the flickering issue for me
the long term support of tclock is amazing, i will continue to use it daily

**Comment by kewlfft** [comment]
i have one minor comment: my customized format is quite long and there is too much size allocated to it, i need to give a negative arrangement width adjustment to make it fit well. The size is well calculated for a Courier font but for a Tahoma font with spaces it gives too much room it seems.
is the negative arrangement width the right way to go?

**Comment by k-takata** [comment]
Please try this.
https://github.com/k-takata/TClockLight/releases/tag/tclocklight-kt160829-beta
This should calculate the clock width better than the previous version.

The clock size becomes wider when the width of `0` is wider than the width of a space character.

If you use a format which has padding with space like `_h:nn`, and when the time changes form 9:59 to 10:00, the displayed string changes form `␣9:59` to `10:00`. If the width of `␣` and `1` are different, the clock width will be changed. I think this is annoying.
To avoid changing the clock width, `09:59` is used instead of `␣9:59` when calculating the clock width.
The previous version replaces all spaces to `0` when calculating the clock width, but the latest version only replaces spaces used for padding.

> is the negative arrangement width the right way to go?

Yes. If the clock width is still wide, you can use the negative value.

**Comment by kewlfft** [comment]
with the new version the clock width is much better without any adjustment width thanks!

**Comment by k-takata** [comment]
[tclocklight-kt160911](https://github.com/k-takata/TClockLight/releases/tag/tclocklight-kt160911) has been released.

Actually still one limitation exists: clocks on sub displays are not supported.
But closing this for now.
