### ISSUE TITLE
マルチディスプレイ環境でメインディスプレイにだけTClockLightが適応する

### ISSUE THREAD

**Issue by pokemonleo** [k-takata/TClockLight#2]
問題というか、alpha版の報告みたいなものです

マルチディスプレイ環境下、Windows 10では全てのディスプレイにタスクバーが表示できるよう設定できますが、時計はメインディスプレイだけに表示していました
Anniversary Update後、複数のタスクバーにも時計が表示するようになりましたが、TClockLightはメインディスプレイの時計にだけ表示
他の時計はデフォルトのものです

**Comment by k-takata** [comment]
報告ありがとうございます。
現在のTClockLightは、時計が1つだけという前提で作られているので、複数の時計に対応させるのはかなり大変そうな感じがしています。

**Comment by pokemonleo** [comment]
遅れて申し訳ありません、そして返信ありがとうございます。
Win 10 AU 後にも tclock をサポートして頂き、本当にありがとうございます。（現時点での）仕様の確認も取れたということで、仕様扱いとして、この issue を閉じようと思います。
