### ISSUE TITLE
The software asks for the  language file. But I cant find it.

### ISSUE THREAD

**Issue by apometron** [k-takata/TClockLight#5]
Where I should look for the language file?

I seem do not find it everywhere.

Please, help.

But in English please, because I dont understand Japanese.

**Comment by k-takata** [comment]
After unpack tclocklight-kt160911.zip, you will find 3 folders: lang, x64 and x86.
Then move all files under x64 or x86 (it depends on your OS) to the folder you unpacked.
The lang folder contains the language files.
