### ISSUE TITLE
Compiling under Windows 10 64bits gives error > my possible solution

### ISSUE THREAD

**Issue by EdNess** [k-takata/TClockLight#6]
Hi K-Takata,

Thank you for continueing this great program !!
I was gladly i found this one. The Tclock Redux shows up everywhere when I searched for Tclock but for me that one is far too big....TClock light does show up but mainly the older versions. When I searched for Tclockch I came to your website en redirected to this site....
But that's not the problem I encountered.
When compiling on my 64 bits computer with Windows 10, with the NMake.exe of Visual Studio 2015 the compile gave an error.
The 32 bits went Ok, but the 64 bits gave en error:
"main2.obj : error LNK2019: unresolved external symbol strcmp referenced in function CheckTCDLL
..\out64\tclock.exe : fatal error LNK1120: 1 unresolved externals"

A search on internet gave me the reason.
Windows 10 uses UWP (Universal Windows Platform)...
CRT funtions are not supported anymore in UWP (64 bits). See this link:
https://docs.microsoft.com/en-us/cpp/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps.
"strcmp" is such a CRT function.
The solution should be to use unicode functions.
See this site:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms647465(v=vs.85).aspx

So I replaced ALL "strcmp" into the Windows (unicode) function "lstrcmp".
After that the compiling went ok !! still also for the 32 bits !!!

I replaced strcmp in the next files.
\source\common\tclang.c
\source\exe\main2.c
\source\player\main.c
\source\timer\main.c

Maybe you could have a look if that solution is ok. And test things out,
I'm a newby for C(++) programming. But I've been programming for many years in VBA and VB.

Also I made 2 different compile batches for the 32 an 64 bits compile.
Both calls there own vcvars32.bat or vcvars64.bat to set Visual Studio variables before compiling.

Hope that my solution is the right one.

Ed (Netherlands)

**Comment by k-takata** [comment]
I also compiled TClock on Windows 10 with Visual Studio 2015, but it built fine without any errors (both 32 and 64 bits).
Before VS2015, `strcmp()` was included in `libcmt.lib`, however, since VS2015 it is included in `libucrt.lib`. Current makefiles detect the VS version and link the library automatically. E.g.:

https://github.com/k-takata/TClockLight/blob/0bc4eb7719a4ba0ea868bbfbfcd2a4df07971250/source/exe/tclock.mak#L52-L54

Did you run `nmake` in the `source` directory? If you run `nmake` in `exe` or other subdirectories, it won't work.

**Comment by EdNess** [comment]
Hi,
Thanx for your reply. And thanx for keeping up this great program !!!!

Yes I compiled from within the source folder
In the tclock.mak from the zip this is what was at line 53:
**LIBS=$(LIBS) libvcruntime.lib** 
So this was the problem I think. (missing libucrt.lib at the end of the line)
I changed this line in the .mak files of tclock, player and timer
I renamed all lstrcmp back to strcmp an now ist WORKING !!!

The file I downloaded was: TClockLight-tclocklight-kt160911.zip
(downloaded from: https://github.com/k-takata/TClockLight/releases)

Ik just saw that you already wrote this in code section...
I just found out that the structure of git-hub is somewhat confusing:
https://github.com/k-takata/TClockLight/releases
--> here you see the zip files to download under tab Code but also see the tab Issues...I downloaded the zip form this code tab..
https://github.com/k-takata/TClockLight/
--> here you see the files and your comments under tab Code but also see the tab Issues...
I better should have taken the files from there.
Ik will do that now...

Shame on me. I am new to GitHub and didn't know this...
Sorry for that... Hahaha could have spared me some search time..:-)

Thanx again and have a nice day !!!

**Comment by k-takata** [comment]
I fixed the problem after the latest release (kt160911), but I haven't released a new version which includes the fix.
You can download the latest source by using `git` command or from the following URL:
https://github.com/k-takata/TClockLight/archive/master.zip
