### ISSUE TITLE
site tclock2ch.no.land.to returns error 503

### ISSUE THREAD

**Issue by kewlfft** [k-takata/TClockLight#7]
The site http://tclock2ch.no.land.to/ referred to in the readme returns error 503.

**Comment by k-takata** [comment]
I don't see the error.

**Comment by kewlfft** [comment]
Please see:
https://downforeveryoneorjustme.com/tclock2ch.no.land.to
It confirms the site is down.

**Comment by k-takata** [comment]
It says:
> It's just you. tclock2ch.no.land.to is up.

**Comment by k-takata** [comment]
Anyway, tclock2ch.no.land.to is not managed by me, so there's nothing I can do, even it is down.

**Comment by kewlfft** [comment]
Very strange:
> Is tclock2ch.no.land.to down right now?
> It's not just you! tclock2ch.no.land.to is down.

It would be to update the readme, but no problem to close it, up to you.
